/**
 * Draft a release-notes section from the commits since the last tag.
 *
 *   node tools/release-notes.mjs 0.6.0           print the draft
 *   node tools/release-notes.mjs 0.6.0 --write   prepend it to RELEASE-NOTES.md
 *   node tools/release-notes.mjs 0.6.0 --since v0.5.2
 *
 * ⚠ **It produces a DRAFT, and the draft is the least interesting part.** Commit subjects are
 * written for the person reading the diff; release notes are for a GM who wants to know what
 * changed at their table. Every line here needs rewriting by someone who knows which of these the
 * players will actually notice. The gate in `tools/preflight.mjs` checks only that a section for
 * the version EXISTS — it cannot check that it says anything useful.
 *
 * ⚠ **A rules change is not a bullet like any other.** When a release changes how a rule resolves,
 * say so plainly and cite the book and printed page, because a GM mid-campaign needs to know their
 * numbers moved. This is the same standard the rest of the project holds: name the book and page.
 *
 * ⚠ **It writes nothing but RELEASE-NOTES.md, and never commits.**
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FILE = path.join(ROOT, 'RELEASE-NOTES.md');

const args  = process.argv.slice(2);
const write = args.includes('--write');
const version = (args.find(a => !a.startsWith('--')) ?? '').replace(/^v/, '');
const sinceArg = args.indexOf('--since') >= 0 ? args[args.indexOf('--since') + 1] : null;

if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error('usage: node tools/release-notes.mjs <x.y.z> [--write] [--since <tag>]');
  process.exit(2);
}

const git = (...a) => {
  // stderr is swallowed on purpose: `git describe` says "No names found" before the first tag,
  // which is the normal case for a first release and not something to print at the user.
  try { return execFileSync('git', a, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim(); }
  catch { return ''; }
};

// The previous tag, or the whole history when there has never been one (the first release).
const since = sinceArg ?? git('describe', '--tags', '--abbrev=0') ?? '';
const range = since ? `${since}..HEAD` : '';
const log = git('log', '--no-merges', '--format=%h\x1f%s', ...(range ? [range] : []))
  .split('\n').filter(Boolean)
  .map(l => { const [hash, subject] = l.split('\x1f'); return { hash, subject }; });

/**
 * Group by the shape this project's subjects already use — "TODO 53: …", "Fix: …", "TESTING: …".
 * ⚠ A subject that fits no bucket lands in "Other" rather than being dropped: a release note that
 * quietly omits a change is worse than an untidy one.
 */
const buckets = { feature: [], fix: [], rules: [], docs: [], tests: [], tooling: [], other: [] };
const todoNumbers = new Set();

for (const c of log) {
  const s = c.subject;
  const todo = s.match(/\bTODO\s+(\d+)/i);
  if (todo) todoNumbers.add(Number(todo[1]));
  if (/^(fix|bug)\b|^fix:/i.test(s))                     buckets.fix.push(c);
  else if (/^TODO\s+\d+/i.test(s))                       buckets.feature.push(c);
  else if (/\b(SR3|M&M|MITS|CC|R3|MDF)\s*p\.\d+/i.test(s)) buckets.rules.push(c);
  else if (/^(TESTING|tests?|e2e)\b/i.test(s))           buckets.tests.push(c);
  else if (/^(docs?|CLAUDE|README|guides)\b/i.test(s))   buckets.docs.push(c);
  else if (/^(tools?|build|packs?|release|ci)\b/i.test(s)) buckets.tooling.push(c);
  else                                                    buckets.other.push(c);
}

const section = (title, list) => list.length
  ? `### ${title}\n\n${list.map(c => `- ${c.subject} (\`${c.hash}\`)`).join('\n')}\n\n` : '';

const today = new Date().toISOString().slice(0, 10);
const draft = `## ${version} — ${today}

<!-- ⚠ DRAFT, generated by tools/release-notes.mjs from ${since || 'the start of history'}..HEAD.
     Rewrite it for a GM, not for someone reading the diff. Delete what nobody will notice, and
     for anything that CHANGES HOW A RULE RESOLVES, say so plainly and cite the book and printed
     page — a table mid-campaign needs to know their numbers moved. Then delete this comment. -->

${section('Features', buckets.feature)}${section('Rules', buckets.rules)}${section('Fixes', buckets.fix)}${section('Tests', buckets.tests)}${section('Docs & guides', buckets.docs)}${section('Tooling', buckets.tooling)}${section('Other', buckets.other)}`;

const summary = `${log.length} commit(s) since ${since || 'the start of history'}`
  + (todoNumbers.size ? `; TODO ${[...todoNumbers].sort((a, b) => a - b).join(', ')}` : '');

if (!write) {
  console.log(draft);
  console.error(`\n(${summary}. Pass --write to prepend this to RELEASE-NOTES.md.)`);
  process.exit(0);
}

const header = '# Release notes\n\nWhat changed, for the people running games with it. Newest first.\n\n';
if (!existsSync(FILE)) {
  writeFileSync(FILE, header + draft, 'utf8');
  console.log(`created RELEASE-NOTES.md with ${version} — ${summary}`);
} else {
  const body = readFileSync(FILE, 'utf8');
  if (new RegExp(`^##\\s+v?${version.replace(/\./g, '\\.')}\\b`, 'm').test(body)) {
    console.error(`RELEASE-NOTES.md already has a "## ${version}" section — not touching it.`);
    process.exit(1);
  }
  const at = body.indexOf('\n## ');
  writeFileSync(FILE, at < 0 ? `${body.trimEnd()}\n\n${draft}` : body.slice(0, at + 1) + draft + body.slice(at + 1), 'utf8');
  console.log(`prepended ${version} to RELEASE-NOTES.md — ${summary}`);
}
console.log('⚠ Now read it and rewrite it. The preflight gate proves the section exists, not that it is any good.');
